### ISSUE TITLE
pls fix font-size to match proper tailwind classes

### ISSUE THREAD

**Issue by diomed** [hunghg255/css2tailwind#1]
converts the font-size to text-[24px] instead of text-2xl...

**Comment by hunghg255** [comment]
thanks you, but what are you mean

**Comment by hunghg255** [comment]
![Screenshot 2023-07-06 at 09 16 36](https://github.com/hunghg255/css2tailwind/assets/42096908/823f6658-b0a0-40cd-a1aa-2fdd168d371a)
you mean this one, right

**Comment by diomed** [comment]
yes, man. I meant that.
because people were complaining you dont even use proper class names.
