### ISSUE TITLE
The inset attribute is lost after the conversion

### ISSUE THREAD

**Issue by tsq1990** [hunghg255/css2tailwind#2]
before convert:
`
        position: absolute;
        inset: 0;
        color: #e4eaff;
        font-size: 16px;
        display: flex;
        align-items: center;
        justify-content: center;
`

after convert:
`
        absolute text-[#e4eaff] text-base flex items-center justify-center
`

**Comment by hunghg255** [comment]
thank you for your feedback. I will fix this later

**Comment by hunghg255** [comment]
@tsq1990 I updated the convert inset. you can upgrade the package. thanks
