### ISSUE TITLE
The 'min-height' attribute is failure after the conversion

### ISSUE THREAD

**Issue by tsq1990** [hunghg255/css2tailwind#5]
convert before:
 `flex: 1; min-height: 0; margin: 0 -10px; position: relative; overflow-y: auto; overflow-x: hidden;`

 convert after:
`flex-[1] [0] -mx-[10px] my-[0] relative overflow-y-auto overflow-x-hidden`

**Comment by hunghg255** [comment]
@tsq1990 thanks for report, I fixed this error
